### ISSUE TITLE
The upgrades dont work properly

### ISSUE THREAD

**Issue by 789soar** [Capybaric123/Mining-Simulator#5]
The upgrades dont work properly

**Comment by Capybaric123** [comment]
The upgrades were fixed and now they can be upgraded as much as you want without the drop script breaking because the chances are more then 1.
Here you can see how much ruby's I have with the upgrades:

![Снимок экрана (18)](https://github.com/user-attachments/assets/69c7891a-7edd-47a4-8d50-c125d8d5aabe)
